CREATE DATABASE QLBD
USE QLBD
--San(MaSan, TenSan, DiaChi)
CREATE TABLE SAN
(
	MASAN VARCHAR(3) PRIMARY KEY,
	TENSAN NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(50) NOT NULL
)

--Doi(MaDoi, TenDoi, MaSan)
CREATE TABLE DOI
(
	MADOI VARCHAR(3) PRIMARY KEY,
	TENDOI NVARCHAR(50) NOT NULL,
	MASAN VARCHAR(3)
	FOREIGN KEY(MASAN) REFERENCES SAN(MASAN)
)
--TranDau(MaTD, MaSan, Ngay, Gio)
CREATE TABLE TRANDAU
(
	MATD VARCHAR(2) PRIMARY KEY,
	MASAN VARCHAR(3),
	NGAY DATE NOT NULL,
	GIO TIME NOT NULL,
	FOREIGN KEY (MASAN) REFERENCES SAN(MASAN)
)
--CT_TranDau(MaTD, MaDoi, SoBanThang).
CREATE TABLE CT_TRANDAU
(
	MATD VARCHAR(2),
	MADOI VARCHAR(3),
	SOBANTHANG TINYINT CHECK (SOBANTHANG >= 0),
	PRIMARY KEY (MATD, MADOI),
	FOREIGN KEY (MATD) REFERENCES TRANDAU(MATD),
	FOREIGN KEY (MADOI) REFERENCES DOI(MADOI)
)

SELECT * FROM SAN
SELECT * FROM DOI
SELECT * FROM TRANDAU
SELECT * FROM CT_TRANDAU

--1-	In số trận đấu mà mỗi đội đã thi đấu. Hiển thị:  MaDoi, TenDoi.
SELECT TENDOI, B.[SO TRAN THI DAU]
FROM DOI A, (SELECT MADOI, COUNT(MADOI) AS [SO TRAN THI DAU]
	FROM CT_TRANDAU
	GROUP BY MADOI) B
WHERE A.MADOI = B.MADOI

--2-	In kết quả trận đấu theo tỷ số:
--MaTran  | Đội trận đấu | Tỷ số
--  01         | VN-TL         | 3-1
SELECT A.MATD, (A.MADOI + '-' + B.MADOI) AS DOI, (STR(A.SOBANTHANG,2) + '-' + STR(B.SOBANTHANG,1)) AS TISO
FROM CT_TRANDAU A, CT_TRANDAU B
WHERE A.MATD = B.MATD AND A.MADOI > B.MADOI

--3-	In kết quả mỗi trận theo điểm:
--MaTran  | Doi  | Diem
--01	   | VN  |  3
--01         | TL   |  0 
SELECT A.MATD, MADOI, (CASE SOBANTHANG WHEN A.LN THEN (CASE WHEN SOBANTHANG = A.NN THEN 1 ELSE 3 END) ELSE 0 END) AS [DIEM]
FROM
(SELECT MATD, MAX(SOBANTHANG) AS LN, MIN(SOBANTHANG) AS NN
FROM CT_TRANDAU
GROUP BY MATD) A
LEFT JOIN
CT_TRANDAU B
ON A.MATD = B.MATD;

SELECT A.MADOI, A.MATD, [DIEM] = CASE WHEN A.SOBANTHANG>B.SOBANTHANG THEN 3 WHEN A.SOBANTHANG = B.SOBANTHANG THEN 1 ELSE 0 END
FROM CT_TRANDAU A, CT_TRANDAU B
WHERE A.MATD = B.MATD AND A.MADOI <> B.MADOI

--4-	In mã đội, tên đội, tổng số điểm:
--      VN   |  Việt Nam  | 6   
SELECT TAM.MADOI, TAM.TENDOI ,SUM(TAM.DIEM) AS DIEM
FROM 
(SELECT A.MATD, A.MADOI, DOI.TENDOI, [DIEM] = CASE WHEN A.SOBANTHANG>B.SOBANTHANG THEN 3 WHEN A.SOBANTHANG = B.SOBANTHANG THEN 1 ELSE 0 END
FROM CT_TRANDAU A INNER JOIN CT_TRANDAU B
ON A.MATD = B.MATD AND A.MADOI <> B.MADOI
LEFT JOIN DOI ON DOI.MADOI = A.MADOI) AS TAM
GROUP BY TAM.MADOI, TAM.TENDOI
ORDER BY DIEM DESC

--5-	Sắp xếp danh sách các đội để biết thứ hạng:
--    | MaDoi  | Ten Doi     | Tổng số điểm | Hiệu số bàn thắng
--        VN     |  Viet Nam  |      6                |    7
SELECT TONGDIEM.MADOI, TONGDIEM.TENDOI, TONGDIEM.DIEM, HSBT.HSBT
	FROM
		(SELECT TAM.MADOI, TAM.TENDOI ,SUM(TAM.DIEM) AS DIEM
			FROM 
				(SELECT A.MATD, A.MADOI, DOI.TENDOI, [DIEM] = CASE WHEN A.SOBANTHANG>B.SOBANTHANG THEN 3 WHEN A.SOBANTHANG = B.SOBANTHANG THEN 1 ELSE 0 END
					FROM CT_TRANDAU A INNER JOIN CT_TRANDAU B
						ON A.MATD = B.MATD AND A.MADOI <> B.MADOI
						LEFT JOIN DOI ON DOI.MADOI = A.MADOI
				) AS TAM
						GROUP BY TAM.MADOI, TAM.TENDOI
		) AS TONGDIEM
	INNER JOIN
				(SELECT A.MADOI, (SUM(A.SOBANTHANG) - SUM(B.SOBANTHANG)) AS HSBT
					FROM CT_TRANDAU A, CT_TRANDAU B
						WHERE A.MATD = B.MATD AND A.MADOI <> B.MADOI
							GROUP BY A.MADOI
				) AS HSBT
	ON TONGDIEM.MADOI = HSBT.MADOI
ORDER BY TONGDIEM.DIEM DESC
--6-	Hiển thị các trận chưa đá:
--    Các trận chưa đá:
--       LA - CPC 
--       VN - CPC

SELECT*
FROM CT_TRANDAU A INNER JOIN CT_TRANDAU B
ON A.MATD = B.MATD AND A.MADOI <> B.MADOI
RIGHT JOIN DOI
ON DOI.MADOI = A.MADOI