CREATE DATABASE QLSINHVIEN
USE QLSINHVIEN

--LOP(MaLop, TenLop, SiSo)
CREATE TABLE LOP
(
	MALOP VARCHAR(7) PRIMARY KEY,
	TENLOP NVARCHAR(50) NOT NULL,
	SISO TINYINT CHECK (SISO > 0)
)

----MONHOC(MaMH, TenMH, TCLT, TCTH)
CREATE TABLE MONHOC
(
	MAMH VARCHAR(6) PRIMARY KEY,
	TENMH NVARCHAR(50) NOT NULL,
	TCLT TINYINT CHECK (TCLT > 0),
	TCTH TINYINT CHECK (TCTH >= 0)
)

--SINHVIEN(MSSV, HoTen, NTNS, Phai, MaLop)
CREATE TABLE SINHVIEN
(
	MSSV VARCHAR(15) PRIMARY KEY,
	HOTEN NVARCHAR(50) NOT NULL,
	NTNS DATETIME NOT NULL,
	PHAI CHAR(2)CHECK(PHAI IN (0,1)) DEFAULT 1,
	MALOP VARCHAR(7),
	FOREIGN KEY(MALOP) REFERENCES LOP(MALOP)
)
--DIEMSV(MSSV, MaMH, Diem)
CREATE TABLE DIEMSV
(
	MSSV VARCHAR(15),
	MAMH VARCHAR(6),
	DIEM DECIMAL(3,1) CHECK (DIEM IS NULL OR DIEM >=0 OR DIEM <=10),
	PRIMARY KEY (MSSV, MAMH),
	FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV),
	FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
)

SELECT * FROM LOP
SELECT * FROM MONHOC
SELECT * FROM SINHVIEN
SELECT * FROM DIEMSV


DELETE FROM SINHVIEN


--1-	Thêm một dòng mới vào bảng SINHVIEN với giá trị: 190001	Đào Thị Tuyết Hoa	08/03/2001	0	19DTH02
INSERT INTO SINHVIEN (MSSV,HOTEN,NTNS,PHAI,MALOP)
VALUES (190001,N'Đào Thị Tuyết Hoa','08/03/2001',0,'19DTH02')

--DELETE FROM SINHVIEN WHERE MSSV = 190001

--2-	Hãy đổi tên môn học ‘Lý thuyết đồ thị ’thành ‘Toán rời rạc’.
UPDATE MONHOC
SET TENMH = N'Toán rời rạc'
WHERE TENMH = N'Lý thuyết đồ thị';

--3-	Hiển thị tên các môn học không có thực hành.
SELECT TENMH
FROM MONHOC
WHERE TCTH = 0;

--4-	Hiển thị tên các môn học vừa có lý thuyết, vừa có thực hành.
SELECT TENMH
FROM MONHOC
WHERE TCLT > 0 AND TCTH > 0;

--5-	In ra tên các môn học có ký tự đầu của tên là chữ ‘C’.
SELECT TENMH
FROM MONHOC
WHERE TENMH LIKE 'C%';

--6-	Liệt kê thông tin những sinh viên mà họ chứa chữ ‘Thị’.
SELECT *
FROM SINHVIEN
WHERE HOTEN LIKE N'%Thị%';

--7-	In ra 2 lớp có sĩ số đông nhất (bằng nhiều cách). Hiển thị: Mã lớp, Tên lớp, Sĩ số. Nhận xét?
--CÁCH 1:
SELECT TOP (2) WITH TIES *
FROM LOP
ORDER BY SISO DESC
--CÁCH 2:
SELECT *
FROM LOP
WHERE SISO IN (SELECT MAX(SISO) FROM LOP) OR SISO IN (SELECT MAX(SISO) FROM LOP WHERE SISO < (SELECT MAX(SISO) FROM LOP))
ORDER BY SISO DESC
--CÁCH 3:
SELECT *
FROM LOP
WHERE SISO IN (SELECT MAX(SISO) FROM LOP) OR SISO IN (SELECT MAX(SISO) FROM LOP WHERE SISO NOT IN (SELECT MAX(SISO) FROM LOP))
ORDER BY SISO DESC

--8-	In danh sách SV theo từng lớp: MSSV, Họ tên SV, Năm sinh, Phái (Nam/Nữ).
--CÁCH 1:
SELECT A.MSSV, A.HOTEN, A.NTNS, A.PHAI, A.MALOP
FROM SINHVIEN A,(SELECT MALOP FROM SINHVIEN GROUP BY MALOP) AS B
WHERE A.MALOP = B.MALOP;
--CÁCH 2:
SELECT *
FROM SINHVIEN
WHERE MALOP IN (SELECT MALOP FROM SINHVIEN GROUP BY MALOP);

--9-	Cho biết những sinh viên có tuổi ≥ 20, thông tin gồm: Họ tên sinh viên, Ngày sinh, Tuổi.
SELECT HOTEN, NTNS, (YEAR(GETDATE())-YEAR(NTNS)) AS [TUOI]
FROM SINHVIEN
WHERE (YEAR(GETDATE())-YEAR(NTNS)) >= 20

--10-	Liệt kê tên các môn học SV đã dự thi nhưng chưa có điểm.
SELECT B.MSSV,C.HOTEN,C.MALOP, B.MAMH, A.TENMH
FROM MONHOC A, DIEMSV B, SINHVIEN C
WHERE A.MAMH = B.MAMH AND B.MSSV = C.MSSV AND B.DIEM IS NULL;

--11-	Liệt kê kết quả học tập của SV có mã số 170001. Hiển thị: MSSV, HoTen, TenMH, Diem.
SELECT A.MSSV, A.HOTEN, A.MALOP, C.TENMH, B.DIEM
FROM SINHVIEN A, DIEMSV B, MONHOC C
WHERE A.MSSV = B.MSSV AND C.MAMH = B.MAMH AND A.MSSV = 170001;

--12-	Liệt kê tên sinh viên và mã môn học mà sv đó đăng ký với điểm trên 7 điểm.
SELECT HOTEN, MAMH, DIEM
FROM SINHVIEN A, DIEMSV B
WHERE A.MSSV = B.MSSV AND B.DIEM > 7;

--13-	Liệt tên môn học cùng số lượng SV đã học và đã có điểm.
SELECT A.TENMH, C.SLSV AS [SO LUONG SINH VIEN]
FROM MONHOC A, (SELECT MAMH, COUNT(MAMH) AS SLSV FROM DIEMSV WHERE DIEM IS NOT NULL GROUP BY MAMH) AS C
WHERE A.MAMH = C.MAMH

--14-	Liệt kê tên SV và điểm trung bình của SV đó.
SELECT A.HOTEN, B.DTB
FROM SINHVIEN A, (SELECT MSSV, (SUM(DIEM)/COUNT(MSSV)) AS DTB FROM DIEMSV GROUP BY MSSV) AS B
WHERE A.MSSV = B.MSSV

--15-	Liệt kê tên sinh viên đạt điểm cao nhất của môn học ‘Kỹ thuật lập trình’.
SELECT TOP(1) WITH TIES A.MSSV, B.HOTEN
FROM DIEMSV A, SINHVIEN B
WHERE A.MSSV = B.MSSV AND MAMH IN (SELECT MAMH FROM MONHOC WHERE TENMH = N'Kỹ thuật lập trình')
ORDER BY DIEM DESC

--16-	Liệt kê tên SV có điểm trung bình cao nhất.
SELECT TOP(1) WITH TIES A.HOTEN, B.DTB
FROM SINHVIEN A, (SELECT MSSV, (SUM(DIEM)/COUNT(MSSV)) AS DTB FROM DIEMSV GROUP BY MSSV) AS B
WHERE A.MSSV = B.MSSV
ORDER BY B.DTB DESC

--17-	Liệt kê tên SV chưa học môn ‘Toán rời rạc’.
SELECT HOTEN
FROM SINHVIEN
WHERE MSSV NOT IN (SELECT MSSV FROM DIEMSV WHERE MAMH IN (SELECT MAMH FROM MONHOC WHERE TENMH = N'Toán rời rạc'))

--18-	Cho biết sinh viên có năm sinh cùng với sinh viên tên ‘Danh’.
SELECT HOTEN
FROM SINHVIEN
WHERE YEAR(NTNS) = (SELECT YEAR(NTNS) FROM SINHVIEN WHERE HOTEN LIKE '%Danh') AND HOTEN NOT LIKE '%Danh'

--19-	Cho biết tổng sinh viên và tổng số sinh viên nữ.
SELECT COUNT(SINHVIEN.MSSV) AS[TONG SO SV],(SELECT COUNT(SINHVIEN.MSSV) FROM SINHVIEN WHERE SINHVIEN.PHAI=0)AS[TONG SO SV NU]
FROM SINHVIEN

--20-	Cho biết danh sách các sinh viên rớt ít nhất 1 môn.
SELECT *
FROM SINHVIEN A, DIEMSV B
WHERE A.MSSV = B.MSSV AND B.DIEM < 4

--21-	Cho biết MSSV, Họ tên SV đã học và có điểm ít nhất 3 môn.
SELECT A.MSSV, A.HOTEN
FROM SINHVIEN A, (SELECT MSSV FROM DIEMSV WHERE DIEM IS NOT NULL GROUP BY MSSV HAVING COUNT(MSSV) >= 3) AS B
WHERE A.MSSV = B.MSSV

--22-	In danh sách sinh viên có điểm môn ‘Kỹ thuật lập trình’ cao nhất theo từng lớp.
SELECT SINHVIEN.MSSV, SINHVIEN.HOTEN, A.MALOP, MONHOC.TENMH, DIEM
FROM
(SELECT MALOP, MAMH, MAX(DIEM) AS LN
FROM SINHVIEN, DIEMSV
WHERE SINHVIEN.MSSV = DIEMSV.MSSV AND DIEMSV.DIEM IS NOT NULL AND MAMH IN (SELECT MAMH FROM MONHOC WHERE TENMH = N'Kỹ thuật lập trình')
GROUP BY MALOP, MAMH) AS A
LEFT JOIN MONHOC
ON MONHOC.MAMH = A.MAMH
LEFT JOIN DIEMSV
ON DIEMSV.DIEM = A.LN AND DIEMSV.MAMH = A.MAMH
LEFT JOIN SINHVIEN
ON SINHVIEN.MSSV = DIEMSV.MSSV


--23-	In danh sách sinh viên có điểm cao nhất theo từng môn, từng lớp.
SELECT A.MSSV, HOTEN, CUNGL.MALOP, MONHOC.TENMH, DIEM
FROM
(SELECT MALOP, MAMH, MAX(DIEM) AS LN
FROM DIEMSV, SINHVIEN
WHERE DIEMSV.MSSV = SINHVIEN.MSSV AND DIEM IS NOT NULL
GROUP BY MAMH, MALOP) AS MAXSUB
LEFT JOIN
MONHOC
ON MONHOC.MAMH = MAXSUB.MAMH
LEFT JOIN
DIEMSV A
ON A.MAMH = MAXSUB.MAMH AND A.DIEM = MAXSUB.LN
LEFT JOIN
SINHVIEN B
ON A.MSSV = B.MSSV AND B.MALOP = MAXSUB.MALOP
LEFT JOIN
(SELECT MALOP
FROM SINHVIEN
GROUP BY MALOP) AS CUNGL
ON B.MALOP = CUNGL.MALOP

--24-	Cho biết những sinh viên đạt điểm cao nhất của từng môn.
SELECT TENMH, DIEM,D.MSSV, HOTEN, MALOP
FROM
(SELECT MAMH, MAX(DIEM) AS LN
FROM DIEMSV
GROUP BY MAMH) AS A
LEFT JOIN MONHOC B
ON A.MAMH = B.MAMH
LEFT JOIN DIEMSV C
ON A.LN = C.DIEM AND B.MAMH = C.MAMH
LEFT JOIN SINHVIEN D
ON D.MSSV = C.MSSV

--25-	Cho biết MSSV, Họ tên SV chưa đăng ký học môn nào.
SELECT MSSV, HOTEN
FROM SINHVIEN
WHERE MSSV NOT IN (SELECT MSSV FROM DIEMSV GROUP BY MSSV)

--26-	Danh sách sinh viên có tất cả các điểm đều 10.
SELECT MSSV, HOTEN
FROM SINHVIEN
WHERE MSSV IN
(SELECT MSSV
FROM DIEMSV
GROUP BY MSSV
HAVING AVG(DIEM) = 10)

--27-	Đếm số sinh viên nam, nữ theo từng lớp.
SELECT A.MALOP, B.NU, C.NAM
FROM 
	(SELECT MALOP, COUNT(PHAI) AS TONGSV FROM SINHVIEN GROUP BY MALOP) AS A
	LEFT JOIN
	(SELECT MALOP, COUNT(PHAI) AS NU
	FROM SINHVIEN
	WHERE PHAI = 0
	GROUP BY MALOP) AS B
	ON A.MALOP = B.MALOP
	LEFT JOIN
	(SELECT MALOP, COUNT(PHAI) AS NAM
	FROM SINHVIEN
	WHERE PHAI = 1
	GROUP BY MALOP) AS C
	ON A.MALOP = C.MALOP;


SELECT B.MALOP, B.NU, C.NAM
FROM 
	(SELECT MALOP, COUNT(PHAI) AS NU
	FROM SINHVIEN
	WHERE PHAI = 0
	GROUP BY MALOP) AS B
	FULL OUTER JOIN
	(SELECT MALOP, COUNT(PHAI) AS NAM
	FROM SINHVIEN
	WHERE PHAI = 1
	GROUP BY MALOP) AS C
	ON B.MALOP = C.MALOP;

--28-	Cho biết những sinh viên đã học tất cả các môn nhưng không rớt môn nào.
SELECT HOTEN
FROM SINHVIEN
WHERE MSSV IN
(SELECT MSSV
FROM DIEMSV
WHERE DIEM >=4
GROUP BY MSSV
HAVING COUNT(MSSV) = (SELECT COUNT(MAMH) FROM MONHOC))

--29-	Xóa tất cả những sinh viên chưa dự thi môn nào.
DELETE FROM SINHVIEN WHERE MSSV NOT IN (SELECT MSSV FROM DIEMSV GROUP BY MSSV)

--30-	Cho biết những môn đã được tất cả các sinh viên đăng ký học.
SELECT MAMH, TENMH
FROM MONHOC
WHERE MAMH IN (
SELECT MAMH
FROM DIEMSV
GROUP BY MAMH
HAVING COUNT(MAMH) = (SELECT COUNT(MSSV) FROM SINHVIEN))


